apps/accounts/urls.py
from django.urls import path
from django.views.generic import TemplateView

from apps.accounts.views import UserRegisterView, UserLoginView, UserLogoutView, OwnProfileView, PublicProfileView, \
    ProfileUpdateView, ActivateAccountView, UserPasswordResetConfirmView, UserPasswordResetView, \
    UserPasswordResetDoneView, UserPasswordResetCompleteView

app_name = 'accounts'

urlpatterns = [
    path('profile/', OwnProfileView.as_view(), name='profile'),
    path('profile/edit', ProfileUpdateView.as_view(), name='profile_edit'),
    path('users/<uuid:pk>/', PublicProfileView.as_view(), name='public_profile'),

    path('register/', UserRegisterView.as_view(), name='register'),
    path('activation_sent/', TemplateView.as_view(
        template_name='accounts/activation_sent.html'), name='activation_sent'),
    path('activate/<uidb64>/<token>/', ActivateAccountView.as_view(), name='activate'),
    path('activation_success/', TemplateView.as_view(
        template_name='accounts/activation_success.html'), name='activation_success'),
    path('activation_invalid/', TemplateView.as_view(
        template_name='accounts/activation_invalid.html'), name='activation_invalid'),

    path('login/', UserLoginView.as_view(), name='login'),
    path('logout/', UserLogoutView.as_view(), name='logout'),

    path('password_reset/', UserPasswordResetView.as_view(), name='password_reset'),
    path('password_reset/done/', UserPasswordResetDoneView.as_view(), name='password_reset_done'),
    path('reset/<uidb64>/<token>/', UserPasswordResetConfirmView.as_view(), name='password_reset_confirm'),
    path('reset/complete/', UserPasswordResetCompleteView.as_view(), name='password_reset_complete'),
]

core/urls.py
from django.conf.urls.static import static
from django.contrib import admin
from django.urls import path, include

from core import settings

urlpatterns = [
    path('admin/', admin.site.urls),
    path('', include('apps.accounts.urls')),
    path('', include('apps.wiki.urls')),
    path('', include('apps.shop.urls')),
]

if settings.DEBUG:
    urlpatterns += static(settings.MEDIA_URL, document_root=settings.MEDIA_ROOT)

apps/accounts/models.py
from django.db import models
from django.contrib.auth.models import AbstractBaseUser, PermissionsMixin

from apps.accounts.managers import CustomUserManager
from apps.common.models import IsDeletedModel


ACCOUNT_TYPE_CHOICES = (
    ('player', 'Player'),
    ('master', 'Master'),
)

class CustomUser(AbstractBaseUser, IsDeletedModel, PermissionsMixin):
    '''
    Кастомная модель пользователя, расширяющая AbstractBaseUser.
    '''

    first_name = models.CharField('Имя', max_length=30)
    last_name = models.CharField('Фамилия', max_length=30)
    email = models.EmailField(unique=True)
    account_type = models.CharField(choices=ACCOUNT_TYPE_CHOICES)

    is_staff = models.BooleanField(default=False)
    is_active = models.BooleanField(default=True)

    USERNAME_FIELD = 'email'
    REQUIRED_FIELDS = ['first_name', 'last_name']

    objects = CustomUserManager()

    @property
    def full_name(self):
        return f"{self.first_name} {self.last_name}"

    def __str__(self):
        return self.full_name


class Player(IsDeletedModel):
    user = models.OneToOneField(CustomUser, on_delete=models.CASCADE)
    avatar = models.ImageField(upload_to='accounts/avatars/', null=True, blank=True)
    nickname = models.CharField('Псевдоним игрока', max_length=30)
    description = models.TextField('Расскажите о себе', max_length=500)


class Master(IsDeletedModel):
    user = models.OneToOneField(CustomUser, on_delete=models.CASCADE)
    avatar = models.ImageField(upload_to='accounts/avatars/', null=True, blank=True)
    nickname = models.CharField('Псевдоним мастера', max_length=30)
    description = models.TextField('Расскажите о себе', max_length=500)

apps/accounts/forms.py
from django import forms

from apps.accounts.models import CustomUser, Player, Master

# формы для редактирования профиля
class UserProfileForm(forms.ModelForm):
    class Meta:
        model = CustomUser
        fields = ['first_name', 'last_name']

class PlayerForm(forms.ModelForm):
    class Meta:
        model = Player
        fields = ['avatar', 'nickname', 'description']

class MasterForm(forms.ModelForm):
    class Meta:
        model = Master
        fields = ['avatar', 'nickname', 'description']


class UserRegisterForm(forms.ModelForm):
    first_name = forms.CharField(label='First Name', max_length=50)
    last_name = forms.CharField(label='Last Name', max_length=50)
    email = forms.EmailField()
    password = forms.CharField(widget=forms.PasswordInput)
    password_confirm = forms.CharField(widget=forms.PasswordInput)
    account_type = forms.ChoiceField(
        label='Тип аккаунта',
        choices=(
            ('player', 'Игрок'),
            ('master', 'Мастер'),),
        widget=forms.RadioSelect, # forms.Select, для выпадающего списка
    )

    class Meta:
        model = CustomUser
        fields = ('email', 'first_name', 'last_name', 'password', 'password_confirm', 'account_type')

    def clean(self):
        cleaned_data = super().clean()
        password = cleaned_data.get('password')
        password_confirm = cleaned_data.get('password_confirm')
        if password and password_confirm and password != password_confirm:
            raise forms.ValidationError("Пароли не совпадают")
        return cleaned_data

    def save(self, commit=True):
        """
        - переносим выбранный account_type в модель;
        - НЕ хэшируем пароль (это делает view через user.set_password()).
        """
        user = super().save(commit=False)
        user.account_type = self.cleaned_data['account_type']
        if commit:
            user.save()
        return user


class UserLoginForm(forms.ModelForm):
    email = forms.EmailField()
    password = forms.CharField(widget=forms.PasswordInput)
    password_confirm = forms.CharField(widget=forms.PasswordInput)

    class Meta:
        model = CustomUser
        fields = ('email', 'password', 'password_confirm')

apps/accounts/views.py
from django.contrib import messages
from django.contrib.auth.forms import AuthenticationForm
from django.contrib.auth.mixins import LoginRequiredMixin, UserPassesTestMixin
from django.contrib.auth.views import LoginView, LogoutView, PasswordResetView, PasswordResetDoneView, \
    PasswordChangeView, PasswordResetConfirmView, PasswordResetCompleteView
from django.conf import settings
from django.core.mail import EmailMultiAlternatives
from django.db import transaction
from django.contrib.auth import login
from django.shortcuts import render, redirect
from django.template.loader import render_to_string
from django.urls import reverse, reverse_lazy
from django.utils.encoding import force_bytes, force_str
from django.utils.http import urlsafe_base64_encode, urlsafe_base64_decode

from django.views import View
from django.views.generic import CreateView, DetailView, UpdateView

from apps.accounts.forms import UserRegisterForm, UserProfileForm, PlayerForm, MasterForm
from apps.accounts.models import CustomUser, Player, Master
from apps.accounts.tokens import activation_token



class OwnProfileView(DetailView, LoginRequiredMixin):
    template_name = 'accounts/own_profile.html'
    context_object_name = 'user_obj'

    def get_object(self):
        queryset = CustomUser.objects.select_related('player', 'master')
        return queryset.get(pk=self.request.user.pk)


class PublicProfileView(DetailView, LoginRequiredMixin):
    model = CustomUser
    template_name = 'accounts/public_profile.html'
    context_object_name = 'user_obj'

    def get_queryset(self):
        # фильтруем только активных
        return CustomUser.objects.select_related('player', 'master').filter(is_active=True)


class ProfileUpdateView(LoginRequiredMixin, UpdateView):
    model = CustomUser
    template_name = 'accounts/profile_edit.html'
    success_url = reverse_lazy('accounts:profile')

    def get(self, request, *args, **kwargs):
        user = request.user
        user_form = UserProfileForm(instance=user)
        role_form = PlayerForm(instance=user.player) if user.account_type == 'player' else MasterForm(instance=user.master)
        return render(request, self.template_name, {'user_form': user_form, 'role_form': role_form})

    def post(self, request, *args, **kwargs):
        user = request.user
        user_form = UserProfileForm(request.POST, request.FILES, instance=user)
        role_form = PlayerForm(request.POST, instance=user.player) if user.account_type == 'player' else MasterForm(request.POST, instance=user.master)

        if user_form.is_valid() and role_form.is_valid():
            with transaction.atomic():
                self.object = user_form.save()
                role_form.save()
            return redirect(self.get_success_url())

        return render(request, self.template_name, {'user_form': user_form, 'role_form': role_form})



class UserRegisterView(CreateView):
    model = CustomUser
    template_name = 'accounts/register.html'
    form_class = UserRegisterForm
    extra_context = {'title': 'Регистрация'}
    success_url = reverse_lazy('accounts:activation_sent') # страница проверки почты

    def form_valid(self, form):
        with transaction.atomic():
            user = form.save(commit=False)
            user.set_password(form.cleaned_data['password'])
            user.is_active = False
            user.save()

            if user.account_type == "player":
                Player.objects.create(
                    user=user,
                    avatar='accounts/avatars/default.png',
                    nickname='Лысый гоблин',
                    description=""
                )
            elif user.account_type == "master":
                Master.objects.create(
                    user=user,
                    avatar='accounts/avatars/default.png',
                    nickname='Крутой лысый гоблин',
                    description="",
                )

            # формируем ссылку активации
            uidb64 = urlsafe_base64_encode(force_bytes(user.pk))
            token = activation_token.make_token(user)
            activate_url = reverse('accounts:activate', kwargs={'uidb64': uidb64, 'token': token})

            # отсылаем письмо
            context = {'user': user, 'activate_url': activate_url}
            subject = "Подтверждение регистрации на Karniway"
            html_body = render_to_string('accounts/email/activation_email.html', context)
            text_body = render_to_string('accounts/email/activation_email.txt', context)

            message = EmailMultiAlternatives(
                subject=subject,
                body=text_body,
                from_email=settings.DEFAULT_FROM_EMAIL,
                to=[user.email]
            )
            message.attach_alternative(html_body, "text/html")
            message.send()

            # не логиним, а ждем подтверждение
            return redirect(self.success_url)


class ActivateAccountView(View):
    success_url = reverse_lazy('accounts:activation_success')
    invalid_url = reverse_lazy('accounts:activation_invalid')

    def get(self, request, uidb64, token):
        try:
            uid = force_str(urlsafe_base64_decode(uidb64))
            user = CustomUser.objects.get(pk=uid)
        except Exception:
            messages.error(request, "Неверная ссылка активации")

        if activation_token.check_token(user, token):
            if not user.is_active:
                user.is_active = True
                user.save(update_fields=['is_active']) # оптимизируем запрос
            # логин после активации
            login(request, user, backend=settings.AUTHENTICATION_BACKENDS[0])
            messages.success(request, "Аккаунт подтвержден. Добро пожаловать в Karniway :)")
            return redirect(self.success_url)
        else:
            messages.error(request, "Ссылка просрочена или недействиетельна.")
            return redirect(self.invalid_url)


class UserLoginView(LoginView):
    form_class = AuthenticationForm
    template_name = 'accounts/login.html'
    success_url = reverse_lazy('wiki:home_page')
    extra_context = {'title': 'Авторизация'}

class UserLogoutView(LogoutView):
    next_page = reverse_lazy('wiki:home_page')


class UserPasswordResetView(PasswordResetView):
    template_name = 'accounts/password_reset.html'
    email_template_name = 'accounts/email/password_reset_email.txt'
    subject_template_name = 'accounts/email/password_reset_subject.txt'
    success_url = reverse_lazy('accounts:password_reset_done')
    extra_context = {'title': 'Восстановление пароля'}

class UserPasswordResetDoneView(PasswordResetDoneView):
    template_name = 'accounts/password_reset_done.html'


class UserPasswordResetConfirmView(PasswordResetConfirmView):
    template_name = 'accounts/password_reset_confirm.html'
    success_url = reverse_lazy('accounts:password_reset_complete')


class UserPasswordResetCompleteView(PasswordResetCompleteView):
    template_name = 'accounts/password_reset_complete.html'

templates/accounts/activation_invalid.html
{% extends 'base.html' %}{% block content %}
<div class="card"><h2>Ссылка недействительна</h2>
<a class="btn" href="{% url 'accounts:register' %}">Повторить регистрацию</a></div>
{% endblock %}

templates/accounts/activation_sent.html
{% extends 'base.html' %}{% block content %}
<div class="card"><h2>Проверьте почту</h2>
<p>Мы отправили письмо с ссылкой для активации аккаунта.</p></div>
{% endblock %}

templates/accounts/activation_success.html
{% extends 'base.html' %}{% block content %}
<div class="card"><h2>Аккаунт подтверждён</h2>
<a class="btn btn-primary" href="{% url 'accounts:profile' %}">Мой профиль</a></div>
{% endblock %}

templates/accounts/login.html
{% extends "base.html" %}
{% load static %}

{% block extra_css %}
<link rel="stylesheet" href="{% static 'css/accounts/auth.css' %}">
{% endblock %}

{% block content %}
<div class="auth-wrap">
  <div class="auth-card">
    <h1>Вход</h1>

    {# общие ошибки формы (например, «Неверный логин или пароль») #}
    {% if form.non_field_errors %}
      <div class="form-errors">
        {% for err in form.non_field_errors %}<p>{{ err }}</p>{% endfor %}
      </div>
    {% endif %}

    <form method="post" action="{% url 'accounts:login' %}">
      {% csrf_token %}

      <div class="field">
        <label for="{{ form.username.id_for_label }}">Email или логин</label>
        {{ form.username }}
        {% if form.username.errors %}
          <div class="field-error">{{ form.username.errors.0 }}</div>
        {% endif %}
      </div>

      <div class="field">
        <label for="{{ form.password.id_for_label }}">Пароль</label>
        {{ form.password }}
        {% if form.password.errors %}
          <div class="field-error">{{ form.password.errors.0 }}</div>
        {% endif %}
      </div>

      {# если захочешь «Запомнить меня», сделаем отдельной задачей (нужно обработать в LoginView) #}
      <!--
      <div class="field checkbox">
        <label><input type="checkbox" name="remember_me"> Запомнить меня</label>
      </div>
      -->

      <div class="actions">
        <button type="submit" class="btn-primary">Войти</button>
        <div class="links">
          <a href="{% url 'accounts:register' %}">Регистрация</a>
          <span class="sep">·</span>
          <a href="{% url 'accounts:password_reset' %}">Забыли пароль?</a>
        </div>
      </div>
    </form>
  </div>
</div>
{% endblock %}

templates/accounts/logout.html
<!DOCTYPE html>
<html lang="en">
<head>
    <meta charset="UTF-8">
    <title>Title</title>
</head>
<body>

</body>
</html>

templates/accounts/own_profile.html
{% extends 'base.html' %}
{% load static %}

{% block extra_css %}
<link rel="stylesheet" href="{% static 'css/accounts/profile.css' %}">
{% endblock %}

{% block content %}
<div class="profile-page">
  <section class="profile-card">
    <div class="profile-header">
      <div class="profile-avatar-wrap">
        {% if user_obj.account_type == 'player' and user_obj.player and user_obj.player.avatar %}
          <img class="profile-avatar" src="{{ user_obj.player.avatar.url }}" alt="Аватар">
        {% elif user_obj.account_type == 'master' and user_obj.master and user_obj.master.avatar %}
          <img class="profile-avatar" src="{{ user_obj.master.avatar.url }}" alt="Аватар">
        {% else %}
          <img class="profile-avatar" src="{% static 'img/avatar_default.svg' %}" alt="Аватар">
        {% endif %}
      </div>

      <div class="profile-title">
        <h1 class="profile-name">{{ user_obj.first_name }} {{ user_obj.last_name }}</h1>
        <div class="profile-sub">
          <span class="role-badge">
            {% if user_obj.account_type == 'player' %}Игрок{% else %}Мастер{% endif %}
          </span>
          {% if user_obj.account_type == 'player' and user_obj.player %}
            <span class="nickname">@{{ user_obj.player.nickname }}</span>
          {% elif user_obj.account_type == 'master' and user_obj.master %}
            <span class="nickname">@{{ user_obj.master.nickname }}</span>
          {% endif %}
        </div>
      </div>

      {% if request.user.pk == user_obj.pk %}
        <div class="profile-actions">
          <a class="btn btn-primary" href="{% url 'accounts:profile_edit' %}">Редактировать профиль</a>
        </div>
      {% endif %}
    </div>

    <div class="profile-body">
      <h3 class="section-title">О себе</h3>
      <p class="profile-description">
        {% if user_obj.account_type == 'player' and user_obj.player %}
          {{ user_obj.player.description|default:"Пока нет описания." }}
        {% elif user_obj.account_type == 'master' and user_obj.master %}
          {{ user_obj.master.description|default:"Пока нет описания." }}
        {% else %}
          Пока нет описания.
        {% endif %}
      </p>
    </div>
  </section>

  <section class="profile-sections">
    <div class="card">
      <h3 class="section-title">Активность</h3>
      <p class="muted">Здесь будет лента постов / кампаний / покупок и т.п.</p>
    </div>
    <div class="card">
      <h3 class="section-title">Достижения</h3>
      <p class="muted">Позже добавим бейджи и статистику.</p>
    </div>
  </section>
</div>
{% endblock %}

templates/accounts/password_reset.html
{% extends "base.html" %}
{% load static %}
{% block extra_css %}<link rel="stylesheet" href="{% static 'css/accounts/auth.css' %}">{% endblock %}
{% block content %}
<div class="auth-wrap">
  <div class="auth-card">
    <h1>Восстановление пароля</h1>
    <p>Укажи ваш email. Вам будет отправлено письмо с подтверждением.</p>
    <form method="post" action="{% url 'accounts:password_reset' %}">
      {% csrf_token %}
      <div class="field">
        <label for="id_email">Email</label>
        {{ form.email }}
        {% if form.email.errors %}<div class="field-error">{{ form.email.errors.0 }}</div>{% endif %}
      </div>
      <div class="actions">
        <button type="submit" class="btn-primary">Отправить</button>
        <div class="links"><a href="{% url 'accounts:login' %}">Войти</a></div>
      </div>
    </form>
  </div>
</div>
{% endblock %}

templates/accounts/password_reset_complete.html
{% extends "base.html" %}
{% load static %}
{% block extra_css %}<link rel="stylesheet" href="{% static 'css/accounts/auth.css' %}">{% endblock %}
{% block content %}
<div class="auth-wrap"><div class="auth-card">
  <h1>Пароль обновлён</h1>
  <p>Теперь можно войти с новым паролем.</p>
  <div class="actions"><div class="links"><a href="{% url 'accounts:login' %}">Войти</a></div></div>
</div></div>
{% endblock %}

templates/accounts/password_reset_confirm.html
{% extends "base.html" %}
{% load static %}
{% block extra_css %}<link rel="stylesheet" href="{% static 'css/accounts/auth.css' %}">{% endblock %}
{% block content %}
<div class="auth-wrap"><div class="auth-card">
  <h1>Новый пароль</h1>

  {% if validlink %}
    <form method="post">
      {% csrf_token %}
      <div class="field">
        <label for="{{ form.new_password1.id_for_label }}">Новый пароль</label>
        {{ form.new_password1 }}
        {% if form.new_password1.errors %}<div class="field-error">{{ form.new_password1.errors.0 }}</div>{% endif %}
      </div>
      <div class="field">
        <label for="{{ form.new_password2.id_for_label }}">Повторите пароль</label>
        {{ form.new_password2 }}
        {% if form.new_password2.errors %}<div class="field-error">{{ form.new_password2.errors.0 }}</div>{% endif %}
      </div>
      <div class="actions">
        <button type="submit" class="btn-primary">Сохранить новый пароль</button>
      </div>
    </form>
  {% else %}
    <div class="form-errors"><p>Ссылка недействительна или устарела.</p></div>
    <div class="actions"><div class="links"><a href="{% url 'accounts:password_reset' %}">Отправить новую ссылку</a></div></div>
  {% endif %}
</div></div>
{% endblock %}

templates/accounts/password_reset_done.html
{% extends "base.html" %}
{% load static %}
{% block extra_css %}<link rel="stylesheet" href="{% static 'css/accounts/auth.css' %}">{% endblock %}
{% block content %}
<div class="auth-wrap"><div class="auth-card">
  <h1>Проверьте почту</h1>
  <p>Если указанный email есть в системе, мы отправили ссылку для сброса пароля.</p>
  <div class="actions"><div class="links"><a href="{% url 'accounts:login' %}">Вернуться к входу</a></div></div>
</div></div>
{% endblock %}

templates/accounts/profile_edit.html
{% extends 'base.html' %}
{% load static %}

{% block extra_css %}
<link rel="stylesheet" href="{% static 'css/accounts/profile.css' %}">
{% endblock %}

{% block content %}
<div class="profile-page">
  <section class="profile-card">
    <div class="profile-header">
      <div class="profile-avatar-wrap">
        {% if request.user.account_type == 'player' and request.user.player and request.user.player.avatar %}
          <img class="profile-avatar" src="{{ request.user.player.avatar.url }}" alt="Аватар">
        {% elif request.user.account_type == 'master' and request.user.master and request.user.master.avatar %}
          <img class="profile-avatar" src="{{ request.user.master.avatar.url }}" alt="Аватар">
        {% else %}
          <img class="profile-avatar" src="{% static 'img/avatar_default.svg' %}" alt="Аватар">
        {% endif %}
      </div>

      <div class="profile-title">
        <h1 class="profile-name">Редактирование профиля</h1>
        <div class="profile-sub">
          <span class="role-badge">
            {% if request.user.account_type == 'player' %}Игрок{% else %}Мастер{% endif %}
          </span>
        </div>
      </div>

      <div class="profile-actions">
        <a class="btn" href="{% url 'accounts:profile' %}">Отмена</a>
      </div>
    </div>

    <div class="profile-body">
      <form method="post" enctype="multipart/form-data" class="profile-form">
        {% csrf_token %}
        {% if user_form.non_field_errors %}
          <div class="form-errors">{{ user_form.non_field_errors }}</div>
        {% endif %}
        {% if role_form.non_field_errors %}
          <div class="form-errors">{{ role_form.non_field_errors }}</div>
        {% endif %}

        <div class="form-grid">
          <div class="form-group">
            <label for="{{ user_form.first_name.id_for_label }}">Имя</label>
            {{ user_form.first_name }}
            {{ user_form.first_name.errors }}
          </div>
          <div class="form-group">
            <label for="{{ user_form.last_name.id_for_label }}">Фамилия</label>
            {{ user_form.last_name }}
            {{ user_form.last_name.errors }}
          </div>
          <div class="form-group span-2">
            <label for="{{ user_form.avatar.id_for_label }}">Аватар</label>
            {{ user_form.avatar }}
            {{ user_form.avatar.errors }}
          </div>

          {% if request.user.account_type == 'player' %}
            <div class="form-group">
              <label for="{{ role_form.nickname.id_for_label }}">Псевдоним</label>
              {{ role_form.nickname }}
              {{ role_form.nickname.errors }}
            </div>
            <div class="form-group span-2">
              <label for="{{ role_form.description.id_for_label }}">О себе</label>
              {{ role_form.description }}
              {{ role_form.description.errors }}
            </div>
          {% else %}
            <div class="form-group">
              <label for="{{ role_form.nickname.id_for_label }}">Псевдоним</label>
              {{ role_form.nickname }}
              {{ role_form.nickname.errors }}
            </div>
            <div class="form-group span-2">
              <label for="{{ role_form.description.id_for_label }}">О себе</label>
              {{ role_form.description }}
              {{ role_form.description.errors }}
            </div>
          {% endif %}
        </div>

        <div class="form-actions">
          <button type="submit" class="btn btn-primary">Сохранить</button>
          <a href="{% url 'accounts:profile' %}" class="btn">Отмена</a>
        </div>
      </form>
    </div>
  </section>

  <section class="profile-sections">
    <div class="card">
      <h3 class="section-title">Предпросмотр</h3>
      <p class="muted">После сохранения изменения появятся в профиле.</p>
    </div>
  </section>
</div>
{% endblock %}

templates/accounts/public_profile.html
{% extends 'base.html' %}
{% load static %}

{% block extra_css %}
<link rel="stylesheet" href="{% static 'css/accounts/profile.css' %}">
{% endblock %}

{% block content %}
<div class="profile-page">
  <section class="profile-card">
    <div class="profile-header">
      <div class="profile-avatar-wrap">
        {% if user_obj.account_type == 'player' and user_obj.player and user_obj.player.avatar %}
          <img class="profile-avatar" src="{{ user_obj.player.avatar.url }}" alt="Аватар">
        {% elif user_obj.account_type == 'master' and user_obj.master and user_obj.master.avatar %}
          <img class="profile-avatar" src="{{ user_obj.master.avatar.url }}" alt="Аватар">
        {% else %}
          <img class="profile-avatar" src="{% static 'img/avatar_default.svg' %}" alt="Аватар">
        {% endif %}
      </div>

      <div class="profile-title">
        <h1 class="profile-name">{{ user_obj.first_name }} {{ user_obj.last_name }}</h1>
        <div class="profile-sub">
          <span class="role-badge">
            {% if user_obj.account_type == 'player' %}Игрок{% else %}Мастер{% endif %}
          </span>
          {% if user_obj.account_type == 'player' and user_obj.player %}
            <span class="nickname">@{{ user_obj.player.nickname }}</span>
          {% elif user_obj.account_type == 'master' and user_obj.master %}
            <span class="nickname">@{{ user_obj.master.nickname }}</span>
          {% endif %}
        </div>
      </div>

      {% if request.user.pk == user_obj.pk %}
        <div class="profile-actions">
          <a class="btn btn-primary" href="{% url 'accounts:profile_edit' %}">Редактировать профиль</a>
        </div>
      {% endif %}
    </div>

    <div class="profile-body">
      <h3 class="section-title">О себе</h3>
      <p class="profile-description">
        {% if user_obj.account_type == 'player' and user_obj.player %}
          {{ user_obj.player.description|default:"Пока нет описания." }}
        {% elif user_obj.account_type == 'master' and user_obj.master %}
          {{ user_obj.master.description|default:"Пока нет описания." }}
        {% else %}
          Пока нет описания.
        {% endif %}
      </p>
    </div>
  </section>

  <section class="profile-sections">
    <div class="card">
      <h3 class="section-title">Активность</h3>
      <p class="muted">Здесь будет лента постов / кампаний / покупок и т.п.</p>
    </div>
    <div class="card">
      <h3 class="section-title">Достижения</h3>
      <p class="muted">Позже добавим бейджи и статистику.</p>
    </div>
  </section>
</div>
{% endblock %}

templates/accounts/register.html
{% extends "base.html" %}
{% load static %}

{% block extra_css %}
<link rel="stylesheet" href="{% static 'css/accounts/auth.css' %}">
{% endblock %}

{% block content %}
<div class="auth-wrap">
  <div class="auth-card">
    <h1>{{ title }}</h1>

    {# вывод ошибок формы (например, email уже занят) #}
    {% if form.non_field_errors %}
      <div class="form-errors">
        {% for err in form.non_field_errors %}<p>{{ err }}</p>{% endfor %}
      </div>
    {% endif %}

    <form method="post" action="{% url 'accounts:register' %}">
      {% csrf_token %}

      <div class="field">
        <label for="{{ form.first_name.id_for_label }}">Имя</label>
        {{ form.first_name }}
        {% if form.first_name.errors %}
          <div class="field-error">{{ form.first_name.errors.0 }}</div>
        {% endif %}
      </div>

      <div class="field">
        <label for="{{ form.last_name.id_for_label }}">Фамилия</label>
        {{ form.last_name }}
        {% if form.last_name.errors %}
          <div class="field-error">{{ form.last_name.errors.0 }}</div>
        {% endif %}
      </div>

      <div class="field">
        <label for="{{ form.email.id_for_label }}">Email</label>
        {{ form.email }}
        {% if form.email.errors %}
          <div class="field-error">{{ form.email.errors.0 }}</div>
        {% endif %}
      </div>

      <div class="field">
        <label for="{{ form.password.id_for_label }}">Пароль</label>
        {{ form.password }}
        {% if form.password.errors %}
          <div class="field-error">{{ form.password.errors.0 }}</div>
        {% endif %}
      </div>

      <div class="field">
        <label for="{{ form.password.id_for_label }}">Подтверждение пароля</label>
        {{ form.password_confirm }}
        {% if form.password.errors %}
          <div class="field-error">{{ form.password.errors.0 }}</div>
        {% endif %}
      </div>

      <div class="field">
        <label for="{{ form.account_type.id_for_label }}">Тип аккаунта</label>
        {{ form.account_type }}
        {% if form.account_type.errors %}
          <div class="field-error">{{ form.account_type.errors.0 }}</div>
        {% endif %}
      </div>

      <div class="actions">
        <button type="submit" class="btn-primary">Зарегистрироваться</button>
        <div class="links">
          <a href="{% url 'accounts:login' %}">Уже есть аккаунт?</a>
        </div>
      </div>
    </form>
  </div>
</div>
{% endblock %}