apps/wiki/urls.py
from django.urls import path

from apps.wiki.views import PostListView, PostDetailView, PostCreateView, PostEditView, \
    CreatureListView, CreatureDetailView, CreatureCreateView, SpellDetailView, SpellListView, SpellCreateView, \
    NewsListView, CreatureDeleteView, SpellDeleteView, PostDeleteView, CreatureUpdateView, SpellUpdateView

app_name = 'wiki'


urlpatterns = [
    path('', NewsListView.as_view(), name='home_page'),

    path('posts/', PostListView.as_view(), name='post_list'),
    path('posts/create/', PostCreateView.as_view(), name='post_create'),
    path('posts/<slug:slug>/', PostDetailView.as_view(), name='post_detail'),
    path('posts/<slug:slug>/edit', PostEditView.as_view(), name='post_edit'),
    path('posts/<slug:slug>/delete', PostDeleteView.as_view(), name='post_delete'),

    path('creatures/', CreatureListView.as_view(), name='creature_list'),
    path('creatures/create/', CreatureCreateView.as_view(), name='creature_create'),
    path('creatures/<slug:slug>/', CreatureDetailView.as_view(), name='creature_detail'),
    path('creatures/<slug:slug>/edit', CreatureUpdateView.as_view(), name='creature_edit'),
    path('creatures/<slug:slug>/delete', CreatureDeleteView.as_view(), name='creature_delete'),

    path('spells/', SpellListView.as_view(), name='spell_list'),
    path('spells/create/', SpellCreateView.as_view(), name='spell_create'),
    path('spells/<slug:slug>/', SpellDetailView.as_view(), name='spell_detail'),
    path('spells/<slug:slug>/edit', SpellUpdateView.as_view(), name='spell_edit'),
    path('spells/<slug:slug>/delete', SpellDeleteView.as_view(), name='spell_delete')
]

core/urls.py
from django.conf.urls.static import static
from django.contrib import admin
from django.urls import path, include

from core import settings

urlpatterns = [
    path('admin/', admin.site.urls),
    path('', include('apps.accounts.urls')),
    path('', include('apps.wiki.urls')),
    path('', include('apps.shop.urls')),
]

if settings.DEBUG:
    urlpatterns += static(settings.MEDIA_URL, document_root=settings.MEDIA_ROOT)

apps/wiki/models.py
from django.db import models
from django.db.models import PositiveIntegerField

from apps.accounts.models import CustomUser
from apps.common.models import IsDeletedModel
from apps.common.utils import unique_slugify


# ПОСТЫ: Категории, Посты

class PostCategory(models.Model):
    name = models.CharField(max_length=50)
    slug = models.SlugField(unique=True, null=False, blank=False)

    class Meta:
        ordering = ['name',]
        verbose_name = "Категория постов"
        verbose_name_plural = "Категории постов"

    def __str__(self):
        return self.name

    def save(self, *args, **kwargs):
        if not self.slug:
            self.slug = unique_slugify(self, self.name, self.slug)
        super().save(*args, **kwargs)


class Post(IsDeletedModel):
    title = models.CharField(max_length=100)
    slug = models.SlugField(max_length=100, unique=True, null=True, blank=True)
    category = models.ForeignKey(PostCategory, on_delete=models.CASCADE, null=True, blank=True)
    text = models.TextField('Текст статьи', max_length=1500)
    image = models.ImageField(upload_to='post_images/', null=True, blank=True)
    author = models.ForeignKey(CustomUser, on_delete=models.CASCADE)

    class Meta:
        ordering = ('title',)
        verbose_name = "Статья"
        verbose_name_plural = "Статьи"

    def __str__(self):
        return self.title

    def save(self, *args, **kwargs):
        if not self.slug:
            self.slug = unique_slugify(self, self.name, self.slug)
        super().save(*args, **kwargs)


class News(IsDeletedModel):
    title = models.CharField('Название', max_length=100)
    slug = models.SlugField('URL', max_length=100, unique=True, null=True, blank=True)
    text = models.TextField('Текст', max_length=1500)

    class Meta:
        ordering = ('title',)
        verbose_name = "Новость"
        verbose_name_plural = "Новости"

    def __str__(self):
        return self.title

    def save(self, *args, **kwargs):
        if not self.slug:
            self.slug = unique_slugify(self, self.name, self.slug)
        super().save(*args, **kwargs)


# СУЩЕСТВА: Категории, существа, атаки, пассивные особенности

class CreatureCategory(models.Model):
    name = models.CharField(max_length=50)
    image = models.ImageField(upload_to='creature_category_images/', null=True, blank=True)

    class Meta:
        ordering = ['name']
        verbose_name = 'Категория существ'
        verbose_name_plural = 'Категории существ'

    def __str__(self):
        return self.name

CREATURE_SIZE_CHOICES = [
    ('tiny', 'Tiny'),
    ('small', 'Small'),
    ('medium', 'Medium'),
    ('large', 'Large'),
    ('giant', 'Giant'),
]

class Creature(IsDeletedModel):
    name = models.CharField('Название существа', max_length=50, unique=True)
    slug = models.SlugField(max_length=100, unique=True, null=True, blank=True)
    description = models.TextField('Описание существа', max_length=1000)
    image = models.ImageField(upload_to='wiki/creature_images/', null=True, blank=True)
    category = models.ForeignKey(CreatureCategory, on_delete=models.CASCADE)

    # characteristic fields
    health = models.PositiveIntegerField('Хиты', default=0)
    armor_class = models.PositiveIntegerField('КД', default=0)
    mastery = models.PositiveIntegerField('Бонус мастерства', choices=((i, f'+{i}') for i in range(1, 11)), default=10)
    speed = models.PositiveIntegerField('Скорость', default=0)
    size = models.CharField(choices=CREATURE_SIZE_CHOICES, default='')
    saving_throws = models.CharField('Спасброски', max_length=500, default='')
    skills = models.CharField('Навыки', max_length=500, default='')
    dangerous_level = models.PositiveIntegerField('Опасность', choices=((i,i) for i in range(1,21)), default=0)

    # stats fields
    strength = models.PositiveIntegerField('Сила', choices=((i, i) for i in range(20, 0, -1)), default=10)
    dexterity = models.PositiveIntegerField('Ловкость', choices=((i, i) for i in range(20, 0, -1)), default=10)
    body_condition = models.PositiveIntegerField('Телосложение', choices=((i, i) for i in range(20, 0, -1)), default=10)
    intelligence = models.PositiveIntegerField('Интеллект', choices=((i, i) for i in range(20, 0, -1)), default=10)
    wisdom = models.PositiveIntegerField('Мудрость', choices=((i, i) for i in range(20, 0, -1)), default=10)
    charisma = models.PositiveIntegerField('Харизма', choices=((i, i) for i in range(20, 0, -1)), default=10)

    class Meta:
        ordering = ('name',)
        verbose_name = 'Существо'
        verbose_name_plural = 'Существа'

    def __str__(self):
        return self.name

    def save(self, *args, **kwargs):
        if not self.slug:
            self.slug = unique_slugify(self, self.name, self.slug)
        super().save(*args, **kwargs)


class CreatureAttack(models.Model):
    creature = models.ForeignKey(Creature, on_delete=models.CASCADE, related_name='attacks')
    name = models.CharField('Название', max_length=20)
    text = models.TextField('Описание', max_length=200)

    class Meta:
        ordering = ('name',)
        verbose_name = 'Атака существа'
        verbose_name_plural = 'Атаки существ'

    def __str__(self):
        return self.name


class CreaturePassive(models.Model):
    creature = models.ForeignKey(Creature, on_delete=models.CASCADE, related_name='passives')
    name = models.CharField('Название', max_length=30)
    text = models.TextField('Описание', max_length=300)

    class Meta:
        ordering = ('name',)
        verbose_name = 'Особенность существа'
        verbose_name_plural = 'Особенности существ'


    def __str__(self):
        return self.name




# ЗАКЛИНАНИЯ: Категории, заклинания, эффекты


class SpellCategory(models.Model):
    name = models.CharField(max_length=50)
    slug = models.SlugField(max_length=60, unique=True, null=True, blank=True)
    image = models.ImageField(upload_to='wiki/spell_category_images/', null=True, blank=True)

    class Meta:
        ordering = ('name',)
        verbose_name = 'Категория заклинаний'
        verbose_name_plural = 'Категории заклинаний'

    def __str__(self):
        return self.name

    def save(self, *args, **kwargs):
        if not self.slug:
            self.slug = unique_slugify(self, self.name, self.slug)
        super().save(*args, **kwargs)

class SpellEffect(models.Model):
    name = models.CharField(max_length=50)
    slug = models.SlugField(max_length=60, unique=True, null=True, blank=True)
    text = models.TextField(max_length=500)

    class Meta:
        ordering = ('name',)
        verbose_name = 'Эффект заклинания'
        verbose_name_plural = 'Эффекты заклинания'

    def __str__(self):
        return self.name

    def save(self, *args, **kwargs):
        if not self.slug:
            self.slug = unique_slugify(self, self.name, self.slug)
        super().save(*args, **kwargs)


class SpellEffectLink(models.Model):
    spell = models.ForeignKey('Spell', on_delete=models.CASCADE)
    effect = models.ForeignKey(SpellEffect, on_delete=models.PROTECT)
    note = models.TextField(max_length=500, null=True, blank=True)

    class Meta:
        unique_together = ('spell', 'effect')
        ordering = ('id',)

    def save(self, *args, **kwargs):
        self.note = self.effect.text
        super().save(*args, **kwargs)


class Spell(IsDeletedModel):
    name = models.CharField('Название', max_length=100)
    slug = models.SlugField('URL', max_length=100, unique=True, null=True, blank=True)
    category = models.ForeignKey(SpellCategory, on_delete=models.CASCADE, related_name='spells')
    description = models.TextField('Описание', max_length=1000)
    image = models.ImageField(upload_to='wiki/spell_images/', null=True, blank=True)
    effects = models.ManyToManyField(SpellEffect, through='SpellEffectLink', related_name='spells', blank=True)

    # Аспекты заклинания
    casting_time = models.CharField('Время накладывания', max_length=100, null=True, blank=True)
    distance = models.CharField('Дистанция', max_length=100, null=True, blank=True, help_text='На себя/10 футов/30 футов')
    duration = models.CharField('Длительность', max_length=100, null=True, blank=True)
    requirements = models.CharField('Требования', max_length=300, default='отсутствуют')
    special_components = models.CharField('Особые компоненты', max_length=300, default='отсутствуют')
    spell_level = models.CharField('Уровень заклинания', max_length=100, choices=(
        ('заговор', 'Заговор'),
        ('1', '1'),
        ('2', '2'),
        ('3', '3'),
        ('4', '4'),
        ('5', '5'),
        ('6', '6'),
    ))

    class Meta:
        ordering = ('name',)
        verbose_name = 'Заклинание'
        verbose_name_plural = 'Заклинания'

    def __str__(self):
        return self.name

    def save(self, *args, **kwargs):
        if not self.slug:
            self.slug = unique_slugify(self, self.name, self.slug)
        super().save(*args, **kwargs)

apps/wiki/forms.py
from django import forms
from django.forms import inlineformset_factory

from apps.wiki.models import Post, Creature, CreatureAttack, CreaturePassive, Spell, SpellEffectLink


# Формы статей
class PostForm(forms.ModelForm):
    class Meta:
        model = Post
        fields = ['title', 'text', 'image']



# Формы существ

class CreatureForm(forms.ModelForm):

    class Meta:
        model = Creature
        fields = ['name', 'description', 'image',
                  'category', 'health', 'armor_class',
                  'speed', 'size', 'saving_throws',
                  'skills', 'dangerous_level', 'mastery',
                  'strength', 'dexterity', 'body_condition',
                  'intelligence', 'wisdom', 'charisma']


class CreatureAttackForm(forms.ModelForm):
    text = forms.CharField(widget=forms.Textarea, initial='Рукопашная атака оружием: + к попаданию, досягаемость 5 футов, одна цель. Попадание: урона.')
    class Meta:
        model = CreatureAttack
        fields = ['name', 'text']


class CreaturePassiveForm(forms.ModelForm):
    class Meta:
        model = CreaturePassive
        fields = ['name', 'text']

# Inline formsets для удобного создания атак и особенностей существ.

CreatureAttackFormSet = forms.inlineformset_factory(
    parent_model=Creature,
    model=CreatureAttack,
    form=CreatureAttackForm,
    extra=1,
    can_delete=True,
    max_num=10,
    validate_max=True,
)

CreaturePassiveFormSet = forms.inlineformset_factory(
    parent_model=Creature,
    model=CreaturePassive,
    form=CreaturePassiveForm,
    extra=1,
    can_delete=True,
    max_num=10,
    validate_max=True,
)

# Формы заклинаний

class SpellForm(forms.ModelForm):
    class Meta:
        model = Spell
        fields = ('name', 'category', 'description', 'image', 'spell_level', 'requirements', 'special_components')
        widgets = {
            'description': forms.Textarea(attrs={'rows': 6}),
            'requirements': forms.Textarea(attrs={'rows': 2}),
            'special_components': forms.Textarea(attrs={'rows': 2}),
        }


class SpellEffectLinkForm(forms.ModelForm):
    class Meta:
        model = SpellEffectLink
        fields = ['effect']
        widgets = {
            'note': forms.Textarea(attrs={'rows': 6, 'style': 'resize: vertical'}),
        }


SpellEffectFormSet = inlineformset_factory(
    parent_model=Spell,
    model=SpellEffectLink,
    form=SpellEffectLinkForm,
    extra=1,
    can_delete=True,
    validate_max=False,
    validate_min=False,
)

templates/wiki/creature_create.html
{% extends "base.html" %}
{% load static %}

{% block extra_css %}
<link rel="stylesheet" href="{% static 'css/wiki/creature_create.css' %}">
{% endblock %}

{% block content %}
<div class="page">
    <div class="page-header">
        <h1 class="title">{{ title }}</h1>
        {% if creature %}
        <a class="btn" href="{% url 'wiki:creature_detail' creature.slug %}"><-Назад</a>
        {% else %}
        <a class="btn" href="{% url 'wiki:creature_list' %}"><-Назад</a>
        {% endif %}
    </div>


    <form method="post" enctype="multipart/form-data" novalidate>
        {% csrf_token %}

        {% if form.non_field_errors %}<div class="card">{{ form.non_field_errors }}</div>{% endif %}
        <div class="main-form">
            <div class="form-left">
                <div class="grid-2">
                    <div class="card">
                        <h3>Основное</h3>
                        {{ form.name.errors }} <label>Название {{ form.name }}</label>
                        {{ form.description.errors }} <label>Описание {{ form.description }}</label>
                        <div class="row">
                            <div>{{ form.image.errors }} <label>Изображение {{ form.image }}</label></div>
                            <div>{{ form.category.errors }} <label>Категория {{ form.category }}</label></div>
                        </div>
                    </div>

                    <div class="card">
                        <h3>Характеристики</h3>
                        <div class="row">
                            <div>{{ form.health.errors }} <label>Хиты {{ form.health }}</label></div>
                            <div>{{ form.armor_class.errors }} <label>КД {{ form.armor_class }}</label></div>
                        </div>
                        <div class="row">
                            <div>{{ form.mastery.errors }} <label>Бонус мастерства {{ form.mastery }}</label></div>
                            <div>{{ form.speed.errors }} <label>Скорость {{ form.speed }}</label></div>
                        </div>
                        <div class="row">
                            <div>{{ form.size.errors }} <label>Размер {{ form.size }}</label></div>
                            <div>{{ form.dangerous_level.errors }} <label>Опасность {{ form.dangerous_level }}</label></div>
                        </div>
                        {{ form.saving_throws.errors }} <label>Спасброски {{ form.saving_throws }}</label>
                        {{ form.skills.errors }} <label>Навыки {{ form.skills }}</label>
                    </div>
                </div>

                <div class="card" style="margin-top:14px;">
                    <h3>Статы</h3>
                    <div class="row">
                        <div>{{ form.strength.errors }} <label>Сила {{ form.strength }}</label></div>
                        <div>{{ form.dexterity.errors }} <label>Ловкость {{ form.dexterity }}</label></div>
                    </div>
                    <div class="row">
                        <div>{{ form.body_condition.errors }} <label>Телосложение {{ form.body_condition }}</label></div>
                        <div>{{ form.intelligence.errors }} <label>Интеллект {{ form.intelligence }}</label></div>
                    </div>
                    <div class="row">
                        <div>{{ form.wisdom.errors }} <label>Мудрость {{ form.wisdom }}</label></div>
                        <div>{{ form.charisma.errors }} <label>Харизма {{ form.charisma }}</label></div>
                    </div>
                </div>
            </div>

            <div class="form-right">
                {# ---------- Атаки ---------- #}
                <div class="card" style="margin-top:14px;">
                    <div class="inline-header">
                        <h3 style="margin:0">Атаки</h3>
                        <button type="button" class="btn add"
                                onclick="addForm('{{ attack_formset.prefix }}','attack-formset','attack-empty')">+ Добавить атаку</button>
                    </div>

                    {{ attack_formset.management_form }}
                    <div id="attack-formset" class="inline-list">
                        {% for f in attack_formset %}
                        <div class="inline-form">
                            {% if f.non_field_errors %}<div class="errorlist">{{ f.non_field_errors }}</div>{% endif %}
                            <div class="row">
                                <div>{{ f.name.errors }} <label>Название {{ f.name }}</label></div>
                                <div>{{ f.text.errors }} <label>Описание {{ f.text }}</label></div>
                            </div>
                            {% if f.DELETE %}<label class="muted">{{ f.DELETE }} удалить</label>{% endif %}
                            {% for hidden in f.hidden_fields %}{{ hidden }}{% endfor %}
                        </div>
                        {% endfor %}
                    </div>
                </div>



                {# ---------- Пассивы ---------- #}
                <div class="card" style="margin-top:14px;">
                    <div class="inline-header">
                        <h3 style="margin:0">Пассивные способности</h3>
                        <button type="button" class="btn add"
                                onclick="addForm('{{ passive_formset.prefix }}','passive-formset','passive-empty')">+ Добавить пассив</button>
                    </div>

                    {{ passive_formset.management_form }}
                    <div id="passive-formset" class="inline-list">
                        {% for f in passive_formset %}
                        <div class="inline-form">
                            {% if f.non_field_errors %}<div class="errorlist">{{ f.non_field_errors }}</div>{% endif %}
                            <div class="row">
                                <div>{{ f.name.errors }} <label>Название {{ f.name }}</label></div>
                                <div>{{ f.text.errors }} <label>Описание {{ f.text }}</label></div>
                            </div>
                            {% if f.DELETE %}<label class="muted">{{ f.DELETE }} удалить</label>{% endif %}
                            {% for hidden in f.hidden_fields %}{{ hidden }}{% endfor %}
                        </div>
                        {% endfor %}
                    </div>
                </div>
            </div>
        </div>

        <template id="passive-empty">
            {{ passive_formset.empty_form.as_p|safe }}
        </template>

        <div class="btns">
            <button class="btn primary" type="submit">Сохранить</button>
            <a class="btn" href="{% url 'wiki:creature_list' %}">Отмена</a>
        </div>
    </form>
</div>

{# Шаблон пустой формы — используем template и |safe, чтобы не было \u003C ... #}
<template id="attack-empty">
    {{ attack_formset.empty_form.as_p|safe }}
</template>

<script>
    function addForm(prefix, containerId, templateId){
      const totalInput = document.getElementById(`id_${prefix}-TOTAL_FORMS`);
      const index = parseInt(totalInput.value, 10);
      const tpl = document.getElementById(templateId).innerHTML.replace(/__prefix__/g, index);
      const wrapper = document.createElement('div');
      wrapper.className = 'inline-form';
      wrapper.innerHTML = tpl;

      // если в empty_form были <p> — перерисуем их красивее: p -> div + label
      // (не обязательно, но делает внешний вид равномерным с остальными)
      const container = document.getElementById(containerId);
      container.appendChild(wrapper);
      totalInput.value = index + 1;
    }
</script>
{% endblock %}

templates/wiki/creature_detail.html
{% extends "base.html" %}
{% load static %}

{% block extra_css %}
<link rel="stylesheet" href="{% static 'css/wiki/creature_detail.css' %}">
{% endblock %}

{% block content %}
<div class="page">
    <div class="page-header">
        <h1 class="title">{{ title }}</h1>
        <a class="btn adding" href="{% url 'wiki:creature_edit' creature.slug %}">Редактировать существо</a>
    </div>
    <div class="detail-grid">
        <div class="card">
            {% if creature.image %}
            <img class="thumb" src="{{ creature.image.url }}" alt="{{ creature.name }}">
            {% else %}
            <img class="thumb" src="{% static 'admin/img/icon-unknown.svg' %}" alt="">
            {% endif %}
            <div class="muted" style="margin-top:10px;">
                Категория: {{ creature.category.name }}<br>
                Размер: {{ creature.get_size_display }}<br>
                Уровень опасности: {{ creature.dangerous_level }}<br>
                Бонус мастерства: {{ creature.get_mastery_display }}
            </div>
        </div>

        <div class="card">
            <h3 style="margin-top:0">Описание</h3>
            <p style="margin:0">{{ creature.description|linebreaksbr }}</p>
        </div>

        <div class="card">
            <h3 style="margin-top:0">Характеристики</h3>
            <div class="grid">
                <div>Хиты</div><div class="mono">{{ creature.health }}</div>
                <div>КД</div><div class="mono">{{ creature.armor_class }}</div>
                <div>Скорость</div><div class="mono">{{ creature.speed }}</div>
                <div>Спасброски</div><div class="mono">{{ creature.saving_throws }}</div>
                <div>Навыки</div><div class="mono">{{ creature.skills }}</div>
            </div>
        </div>

        <div class="card">
            <h3 style="margin-top:0">Параметры</h3>
            <div class="grid">
                <div>Сила</div><div class="mono">{{ creature.strength }}</div>
                <div>Ловкость</div><div class="mono">{{ creature.dexterity }}</div>
                <div>Телосложение</div><div class="mono">{{ creature.body_condition }}</div>
                <div>Интеллект</div><div class="mono">{{ creature.intelligence }}</div>
                <div>Мудрость</div><div class="mono">{{ creature.wisdom }}</div>
                <div>Харизма</div><div class="mono">{{ creature.charisma }}</div>
            </div>
        </div>

        <div class="card">
            <h3 style="margin-top:0">Атаки</h3>
            {% with creature.attacks.all as attacks %}
            {% if attacks %}
            <div class="list">
                {% for a in attacks %}
                <div class="item"><strong>{{ a.name }}</strong><br>{{ a.text|linebreaksbr }}</div>
                {% endfor %}
            </div>
            {% else %}
            <div class="muted">Нет атак.</div>
            {% endif %}
            {% endwith %}
        </div>

        <div class="card">
            <h3 style="margin-top:0">Пассивные способности</h3>
            {% with creature.passives.all as passives %}
            {% if passives %}
            <div class="list">
                {% for p in passives %}
                <div class="item"><strong>{{ p.name }}</strong><br>{{ p.text|linebreaksbr }}</div>
                {% endfor %}
            </div>
            {% else %}
            <div class="muted">Нет пассивов.</div>
            {% endif %}
            {% endwith %}
        </div>

        <div class="bottom-panel">
            <div class="card">
                <a class="btn" href="{% url 'wiki:creature_list' %}">← Вернуться к списку</a>
            </div>
            <a class="btn danger" href="{% url 'wiki:creature_delete' creature.slug %}">Удалить существо</a>
        </div>

    </div>
</div>
{% endblock %}

templates/wiki/creature_list.html
{% extends 'base.html' %}
{% load static %}

{% block extra_css %}
<link rel="stylesheet" href="{% static 'css/wiki/creature_list.css' %}">
{% endblock %}

{% block content %}
<div class="header">
    <h1>{{ title }}</h1>
    <a href="{% url 'wiki:creature_create' %}" class="add-creature">Добавить существо</a>
</div>


<div class="creature-grid">
    {% for creature in creatures %}
    <div class="creature-card">
        <a href="{% url 'wiki:creature_detail' creature.slug %}">
            {% if creature.image %}
            <img src="{{ creature.image.url }}" alt="{{ creature.name }}" class="creature-img">
            {% endif %}

                <h2>{{ creature.name }}</h2>

            <p><strong>Категория: {{ creature.category }}</strong></p>
            <p class="dangerous-level"><strong>Опасность: </strong>{{ creature.dangerous_level }}</p>
            <p>{{ creature.description }}</p>
        </a>
    </div>
    {% empty %}
        <p>Нет существ в бестиарии.</p>
    {% endfor %}
</div>
{% endblock %}

templates/wiki/post_list.html
{% extends 'base.html' %}

{% load static %}

{% block extra_css %}
<link rel="stylesheet" href="{% static 'css/wiki/post_list.css' %}">
{% endblock %}

{% block content %}
<div class="main-content">
    {% for post in posts %}
        <a href="{% url 'wiki:post_detail' post.slug %}" class="post">
            <div class="post-header">
                <h3>{{ post.title }}</h3>
                <p>{{ post.rating }} ★</p>
            </div>

            <div class="post-body">
                <p>{{ post.text }}</p>
            </div>
        </a>

    {% endfor %}
</div>


{% endblock %}

templates/wiki/spell_detail.html
{% extends "base.html" %}
{% load static %}

{% block extra_css %}
<link rel="stylesheet" href="{% static 'css/wiki/spell.css' %}">
{% endblock %}

{% block content %}
<div class="page">
    <div class="page-header">
        <h1 class="title">{{ title }}</h1>
        <a class="btn adding" href="{% url 'wiki:spell_edit' spell.slug %}">Редактировать заклинание</a>
    </div>

    <div class="spell-layout">
        {# LEFT: image + meta #}
        <aside class="card">
            {% if spell.image %}
            <img class="thumb" src="{{ spell.image.url }}" alt="{{ spell.name }}">
            {% endif %}

            <div class="meta">
                <div class="meta-row"><span class="meta-k">Категория</span><span class="meta-v">{{ spell.category }}</span></div>
                <div class="meta-row"><span class="meta-k">Уровень</span><span class="meta-v">{{ spell.spell_level }}</span></div>
                {% if spell.casting_time %}<div class="meta-row"><span class="meta-k">Время</span><span class="meta-v">{{ spell.casting_time }}</span></div>{% endif %}
                {% if spell.distance %}<div class="meta-row"><span class="meta-k">Дистанция</span><span class="meta-v">{{ spell.distance }}</span></div>{% endif %}
                {% if spell.duration %}<div class="meta-row"><span class="meta-k">Длительность</span><span class="meta-v">{{ spell.duration }}</span></div>{% endif %}
                <div class="meta-row"><span class="meta-k">Требования</span><span class="meta-v">{{ spell.requirements }}</span></div>
                <div class="meta-row"><span class="meta-k">Компоненты</span><span class="meta-v">{{ spell.special_components }}</span></div>
            </div>
        </aside>

        {# RIGHT: description + effects #}
        <section class="card">
            <h3>Описание</h3>
            <div class="prose">{{ spell.description|linebreaksbr }}</div>

            <h3 style="margin-top:18px;">Эффекты</h3>
            {% if effect_links %}
            <ul class="effect-list">
                {% for link in effect_links %}
                <li class="effect-item">
                    <span class="badge">{{ link.effect.name }}</span>
                    {% if link.note %}
                    <div class="note">{{ link.note }}</div>
                    {# .note стилизуем так, чтобы переносы строк сохранились #}
                    {% endif %}
                </li>
                {% endfor %}
            </ul>
            {% else %}
            <p class="muted">Эффекты не указаны.</p>
            {% endif %}
        </section>

        <div class="bottom-panel">
            <div class="card card--bare">
                <a class="btn" href="{% url 'wiki:spell_list' %}">← Вернуться к списку</a>
            </div>
            <a class="btn danger" href="{% url 'wiki:spell_delete' spell.slug %}">
                Удалить заклинание
            </a>
        </div>
    </div>
</div>
{% endblock %}